import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// ─── PHOTO TYPE ───────────────────────────────────────────────────────────────
export interface Photo {
  id:       number;
  src:      string;
  category: string;
  alt:      string;
}

// ─── PHOTO DATA ───────────────────────────────────────────────────────────────
// This JSON is auto-generated by `scripts/scan-photos.js` before every
// dev/build run. Just drop images into /public/photos/{category}/ — done.
import raw from "@/data/photos.json";
export const photos: Photo[] = raw;

// ─── TIMELINE ─────────────────────────────────────────────────────────────────
export const timelineItems = [
  {
    id: 1,
    time: "9:00 AM",
    title: "Morning Prayers & Blessings",
    description:
      "The day began with sacred prayers and heartfelt blessings from grandparents and elders, welcoming little Sia into the family with love and grace.",
    icon: "🌸",
    color: "from-pink-100 to-rose-100",
  },
  {
    id: 2,
    time: "10:30 AM",
    title: "The Grand Reveal — She is Sia!",
    description:
      "In a magical moment that moved every heart in the room, her name was announced. The room erupted in joy — our precious princess is Sia.",
    icon: "✨",
    color: "from-amber-50 to-yellow-100",
  },
  {
    id: 3,
    time: "11:30 AM",
    title: "Family Blessings & First Photos",
    description:
      "Grandparents, aunts, uncles, and cousins gathered around — each blessing Sia with love. The photographers captured every smiling, tearful moment.",
    icon: "💝",
    color: "from-rose-50 to-pink-100",
  },
  {
    id: 4,
    time: "1:00 PM",
    title: "A Feast Made with Love",
    description:
      "The celebration continued with a beautiful feast — homemade delicacies prepared with love by family, filling the air with warmth and joy.",
    icon: "🌿",
    color: "from-green-50 to-emerald-100",
  },
  {
    id: 5,
    time: "3:00 PM",
    title: "Candid Laughter & Memories",
    description:
      "The afternoon was filled with laughter, music, and spontaneous moments — the kind that make the best photographs and last a lifetime.",
    icon: "🎵",
    color: "from-purple-50 to-pink-50",
  },
  {
    id: 6,
    time: "5:00 PM",
    title: "Goodbyes & Warm Farewells",
    description:
      "As the golden hour bathed everything in soft light, guests left carrying hearts full of love and memories that will be treasured forever.",
    icon: "🌅",
    color: "from-orange-50 to-amber-100",
  },
];

// ─── DOWNLOAD HELPERS ─────────────────────────────────────────────────────────
export async function downloadPhoto(photo: Photo): Promise<void> {
  const filename = `sia-ceremony-${String(photo.id).padStart(3, "0")}.jpg`;

  // Local files — direct anchor download (fastest, no fetch overhead)
  if (photo.src.startsWith("/")) {
    const a = document.createElement("a");
    a.href   = photo.src;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    return;
  }

  // External URL fallback (picsum placeholders etc.)
  try {
    const res  = await fetch(photo.src);
    const blob = await res.blob();
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  } catch {
    window.open(photo.src, "_blank");
  }
}

// Staggered bulk download — browsers block simultaneous downloads
export async function downloadPhotos(photoList: Photo[]): Promise<void> {
  for (let i = 0; i < photoList.length; i++) {
    await new Promise<void>((resolve) =>
      setTimeout(async () => { await downloadPhoto(photoList[i]); resolve(); }, i * 450)
    );
  }
}
